#!/bin/sh

# Useful aliases
# Try to keep this Fish-compatible, if possible.

# Pesky permissions
alias ffs='eval "sudo -E $(fc -ln -1)"'

# Start R without the startup prompt.

alias R='R --quiet'

# Create aliases for nmcli for easy use of wifi.
alias nmcon='nmcli -p con up id'
alias nmlist='nmcli -p dev wifi'

# Neovim
[ -n "$(command -v nvim)" ] && alias vim='nvim'

# Tmux
alias ta='tmux attach'
alias td='tmux detach'
alias tmux_restart='systemctl --user restart tmux'

# Aura bindings to match Prezto's pacman module.
alias auri='sudo aura --aursync --unsuppress'
alias aurU='sudo aura --aursync --diff --sysupgrade --delmakedeps --unsuppress'
alias aurs='aura --aursync --search'

# fasd
eval "$(fasd --init posix-alias)"
alias v="f -e ${VISUAL}"
alias o='a -e xdg-open'

# Helper aliases/exports when working on Chromium.
# . "${XDG_CONFIG_HOME}/sh/chromium"

# Aliases to edit config files
. "${XDG_CONFIG_HOME}/sh/editrc"
