#!/bin/sh

# Useful aliases
# Try to keep this Fish-compatible, if possible.

# I mess up. A lot.
if test -n "$(command -v thefuck)" ; then
  eval "$(thefuck --alias ffs)"
fi

# Start R without the startup prompt.
alias R='R --quiet'

# Tmux
alias ta='tmux attach'
alias td='tmux detach'
alias tmux_restart='systemctl --user restart tmux'

# Aura bindings to match Prezto's pacman module.
alias auri='sudo aura --aursync --unsuppress'
alias aurU='sudo aura --aursync --diff --sysupgrade --delmakedeps --unsuppress'
alias aurs='aura --aursync --search'

# Distcc / Ccache
alias enable-distcc='ccache --set-config=prefix_command=distcc'
alias disable-distcc='ccache --set-config=prefix_command='

# fasd
# This won't work in fish either.
eval "$(fasd --init posix-alias)"
alias v="f -e ${VISUAL}"
alias o='a -e xdg-open'

# Helper aliases/exports when working on Chromium.
# . "${XDG_CONFIG_HOME}/sh/chromium"

# Aliases to edit config files
. "${XDG_CONFIG_HOME}/sh/editrc"
