#!/bin/sh

# Functions to ease things.

confirm() {
  printf "%s [y/N] " "$1"
  read -r response
  echo "${response}" | grep -qE '^(y|Y|yes|YES)$'
}

# Obviously won't work with sudo; this is a helper to destroy build libraries.
nuke() {
  if confirm "Are you sure you want to remove '$*'?"; then
    rm -rf "$*"
  fi
}
