#!/bin/sh

# Set and export PATH variables


# User-created utilities like shell scripts, or
# locally-installed utilities, e.g. with pip
PATH="${HOME}/.local/bin:${PATH}"
LD_LIBRARY_PATH="${HOME}/.local/lib:${LD_LIBRARY_PATH}"


# Cabal (Haskell)
if test -d "${HOME}/.cabal" ; then
  PATH="${HOME}/.cabal/bin:${PATH}"
fi

# Gem (Ruby)
if test -d "${HOME}/.gem/ruby/2.3.0" ; then
  PATH="${HOME}/.gem/ruby/2.3.0/bin:${PATH}"
fi

# Linuxbrew (if you're sadistic enough to not instead use Nix)
if test -d "${HOME}/.linuxbrew" ; then
  PATH="${HOME}/.linuxbrew/bin:${PATH}"
  PATH="${HOME}/.linuxbrew/sbin:${PATH}"
  LD_LIBRARY_PATH="${HOME}/.linuxbrew/lib:${LD_LIBRARY_PATH}"
  MANPATH="${HOME}/.linuxbrew/share/man:${MANPATH}"
  INFOPATH="${HOME}/.linuxbrew/share/info:${INFOPATH}"
fi


export PATH
export LD_LIBRARY_PATH
if test -n "${MANPATH}" ; then
  export MANPATH
fi
if test -n "${INFOPATH}" ; then
  export INFOPATH
fi
