#!/bin/sh

# Why not have ~/.profile in $HOME? After all, it is read by both bash and zsh.
# Well, it clutters $HOME, and having .zprofile and .bash_profile source it
# makes it clearer when it is being sourced.

# Reset PATH if it gets overridden by profile/rc/login files.
. "${HOME}/.config/sh/path"

# TODO: Create a new file "xdg_dirs" for stuff like this.
# Prevent less from storing history in .lesshst file
LESSHISTFILE="${XDG_CACHE_HOME}/less/history"

# Don't have Ctrl-S/Q mess with the terminal.
stty -ixon
