#!/bin/sh

# A word on checking whether a util is installed:
# Technically `command -v $util` is better as we don't need to know where the
# command is installed, but it is a lot slower.
# Pretty much all the utilities here will be in /usr/bin, especially on Arch
# Linux where /bin and /sbin are just symlinks to /usr/bin.
# As such, test -x /usr/bin/${util} works just as well.

# Attach to existing tmux session if not already in one.
# Doing this early prevents the original shell from executing everything
# beneath until the user detaches.
if test -x /usr/bin/tmux  && test -z "${TMUX}" ; then
    # Bug: On login, this automatically attaches to the linux console
    # which is marginally smaller than the rxvt terminal.
    # Since tmux's window decreases to the smallest one, our window is small
    # until we detach the old linux connection.
    if test "${TERM}" != 'linux'; then
      tmux attach
    fi
fi

. "${HOME}/.config/sh/aliases"
. "${HOME}/.config/sh/functions"

# Base16-shell
# base16_scheme="solarized"
# base16_file="$HOME/.config/base16/shell/base16-${base16_scheme}.dark.sh"
# [[ -s $base16_file ]] && . $base16_file

if test -x /usr/bin/cowsay  && test -x /usr/bin/fortune ; then
    fortune | cowsay -n -f tux
fi
