#!/bin/sh

# A word on checking whether a util is installed:
# Technically `command -v $util` is better as we don't need to know where the
# command is installed, but it is a lot slower.
# Pretty much all the utilities here will be in /usr/bin, especially on Arch
# Linux where /bin and /sbin are just symlinks to /usr/bin.
# As such, test -x /usr/bin/${util} works just as well.

# Attach to existing tmux session if not already in one, or create one if one does not exist.
# Doing this early prevents the original shell from executing everything
# beneath until the user detaches.
if [ -n "$(command -v tmux)" ] && [ -z "${TMUX}" ] && [ "${TERM}" != 'linux' ]; then
	# if the session 'alexandre' already exists, tmux attaches to it; otherwise, it creates a new one.
	tmux new-session -A -s alexandre
fi

. "${HOME}/.config/sh/aliases"

# Base16-shell
# base16_scheme="solarized"
# base16_file="$HOME/.config/base16/shell/base16-${base16_scheme}.dark.sh"
# [[ -s $base16_file ]] && . $base16_file

if test -x /usr/bin/cowsay  && test -x /usr/bin/fortune ; then
    fortune | cowsay -n -f tux
fi
