#!/bin/sh

# Attach to existing tmux session if not already in one, or create one if one does not exist.
# Doing this early prevents the original shell from executing everything
# beneath until the user detaches.
if [ -z "${TMUX}" ] && [ "${TERM}" != 'linux' ]; then
	# if the session 'alexandre' already exists, tmux attaches to it; otherwise, it creates a new one.
	tmux new-session -A -s alexandre
fi

. "${HOME}/.config/sh/aliases"

if [ -r "${XDG_CONFIG_HOME}/sh/optiverrc" ]; then
	. "${XDG_CONFIG_HOME}/sh/optiverrc"
fi
