#!/bin/sh

# Create a tags file in .git for the versioned files.
# This .git/tags file will automatically be picked up by fugitive.vim.

# TODO: If there are other {pid}.tags files, kill these processes.

git_dir="$(git rev-parse --git-dir)"
pid="$$"
trap 'rm -f "${git_dir}/tags.${pid}"' EXIT INT TERM

git ls-files |\
  ctags -L - \
    --links \
    --tag-relative \
    --recurse=no \
    -f "${git_dir}/tags.${pid}"

mv "${git_dir}/tags.${pid}" "${git_dir}/tags"
