#!/bin/sh

bspc monitor -d term web code media misc

bspc config border_width            2
bspc config window_gap              12
bspc config focus_follows_pointer   true

bspc config split_ratio             0.52
bspc config borderless_monocle      true
bspc config gapless_monocle         true

bspc rule -a Chromium       desktop=^2
bspc rule -a mplayer2       floating=on
bspc rule -a Kupfer.py      focus=on
bspc rule -a Screenkey      manage=off
bspc rule -a Conky          sticky=on manage=off lower=on
