#!/bin/sh

bspc monitor -d term web code media steam misc

bspc config border_width            2
bspc config window_gap              12
bspc config focus_follows_pointer   true

bspc config split_ratio             0.52
bspc config borderless_monocle      true
bspc config gapless_monocle         true
bspc config focus_by_distance				true
bspc config history_aware_focus			true

bspc rule -a Chromium       desktop='^2'
bspc rule -a Midori         desktop='^2'

bspc rule -a emacs          desktop='^3'
bspc rule -a gvim           desktop='^3'
bspc rule -a jetbrains-idea-ce desktop='^3'

bspc rule -a Evince         desktop='^4'
bspc rule -a Zathura        desktop='^4'

bspc rule -a mpv            desktop='^4'
bspc rule -a vlc            desktop='^4'

bspc rule -a Steam          desktop='^5'

. "${HOME}/.config/bspwm/lemonbar.conf"
bspc config top_padding "${PANEL_HEIGHT}"
bspc subscribe > "${XDG_RUNTIME_DIR}/lightstatus-fifo" &
