# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

  config.vm.provider 'virtualbox' do |vb|
    vb.gui = true
  end

  if Vagrant.has_plugin?('vagrant-cachier')
    config.cache.scope = :box
  end

end
